### ISSUE TITLE
Unable to open DRM node: No such file or directory

### ISSUE THREAD

**Issue by bill790** [free-electrons/cedrus-frame-test#18]
./v4l2-request-test -v /dev/video0 -m /dev/media0
Config:
 Video path: /dev/video0
 Media path: /dev/media0
 DRM path: /dev/dri/card0
 DRM driver: sun4i-drm
 Slices path: data/bbb-mpeg2
 Slices filename format: slice-%d.dump
 FPS: 0

Preset:
 Name: bbb-mpeg2
 Description: big_buck_bunny_480p_MPEG2_MP2_25fps_1800K.MPG
 License: Creative Commons Attribution 3.0
 Attribution: Blender Foundation | www.blender.org
 Width: 854
 Height: 480
 Frames count: 25
 Format: MPEG2

Media device driver: sun6i-csi
Unable to open DRM node: No such file or directory

**Comment by luusl** [comment]
I have the same problem, but I thought it is a problem of the libva-v4l2-request project. See https://github.com/bootlin/libva-v4l2-request/issues/27#issuecomment-549774341.

**Comment by paulkocialkowski** [comment]
Hi! First off, it looks like using `/dev/video0` will not work for your case, as the node is backed by driver `sun6i-csi` instead of `cedrus`. You certainly have other /dev/video nodes and you need to adjust to the one matching cedrus. It is announced at boot, with a line like:
> cedrus 1c0e000.video-codec: Device registered as /dev/video0

Then, the `Unable to open DRM node: No such file or directory` issue seems to indicate that there is no DRM driver running on your device (or that it failed to initialize). DRM support is a prerequisite for using this tool, as you can see. Most platforms supported by cedrus should also have DRM support, so you probably need to enable it in your kernel config and/or in the board's device-tree file.

Closing since this is not an issue of the tool but a setup issue instead,
