### ISSUE TITLE
fail again

### ISSUE THREAD

**Issue by hyphop** [free-electrons/cedrus-frame-test#3]
hi again i still cant check v4l2-request-test, same error **Unable to set slice parameters control**
```
root@orangepizeroplus2:/tmp# uname -a
Linux orangepizeroplus2 5.0.0-rc3 #1 SMP Wed Jan 23 15:30:40 +07 2019 armv7l GNU/Linux
```
```
root@orangepizeroplus2:/tmp# ./v4l2-request-test 
Config:
 Video path: /dev/video0
 Media path: /dev/media0
 DRM path: /dev/dri/card0
 DRM driver: sun4i-drm
 Slices path: data/bbb-mpeg2
 Slices filename format: slice-%d.dump
 FPS: 0

Preset:
 Name: bbb-mpeg2
 Description: big_buck_bunny_480p_MPEG2_MP2_25fps_1800K.MPG
 License: Creative Commons Attribution 3.0
 Attribution: Blender Foundation | www.blender.org
 Width: 854
 Height: 480
 Frames count: 25
 Format: MPEG2

Media device driver: cedrus
Destination format: NV12 YUV
Scaling video from 854x480 to 1920x1079+0+0

Processing frame 1/25
Loaded 40286 bytes of video slice data
Unable to set control: Invalid argument
**Unable to set slice parameters control**
Unable to set format controls
Unable to decode video frame
```

**Comment by paulkocialkowski** [comment]
Hi, our current master uses the latest changes for the cedrus driver, which includes patches to refer to references using their timestamp. You can find them in the master branch of the media tree at: https://git.linuxtv.org/media_tree.git/

Since the kernel interface is a moving target, userspace can get broken quite easily when used with a previous kernel version. This is why our interface and driver are still in staging (and no longer part of the public API).

**Comment by hyphop** [comment]
plz say me how can get  kernel + v4l2-request-test source which can work together ? i just wanna to see how its work !

**Comment by paulkocialkowski** [comment]
See http://linux-sunxi.org/Mainline_Kernel_Howto for instructions on how to build the kernel and use the kernel tree URL that I mentioned above.

**Comment by hyphop** [comment]
tnx for link but  i know it  )))  kernel compilation/crosscompilation its not problem , ok will try to exlore again what wrong ) tnx

**Comment by paulkocialkowski** [comment]
FYI I have just pushed a release-2019.03 tag on both linux-cedrus and v4l2-request-test, which were tested to work together correctly!
